// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU65CE0FhWi_3TAbL-VDzDsjusGN4E4pM',
    appId: '1:596541630097:web:bc9c2842b30ed076424130',
    messagingSenderId: '596541630097',
    projectId: 'aidly-4d8d4',
    authDomain: 'aidly-4d8d4.firebaseapp.com',
    storageBucket: 'aidly-4d8d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgeHM-mpN5L601p-FUfaQTejunO7RtRjM',
    appId: '1:596541630097:android:271e668a62df3290424130',
    messagingSenderId: '596541630097',
    projectId: 'aidly-4d8d4',
    storageBucket: 'aidly-4d8d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6kDob1OPQ5pyD2dXE4zlOBo5ToRvmlXM',
    appId: '1:596541630097:ios:75cbf01fbaf25e5e424130',
    messagingSenderId: '596541630097',
    projectId: 'aidly-4d8d4',
    storageBucket: 'aidly-4d8d4.firebasestorage.app',
    iosBundleId: 'com.example.aidly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6kDob1OPQ5pyD2dXE4zlOBo5ToRvmlXM',
    appId: '1:596541630097:ios:75cbf01fbaf25e5e424130',
    messagingSenderId: '596541630097',
    projectId: 'aidly-4d8d4',
    storageBucket: 'aidly-4d8d4.firebasestorage.app',
    iosBundleId: 'com.example.aidly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU65CE0FhWi_3TAbL-VDzDsjusGN4E4pM',
    appId: '1:596541630097:web:684d1dcbc0f9df15424130',
    messagingSenderId: '596541630097',
    projectId: 'aidly-4d8d4',
    authDomain: 'aidly-4d8d4.firebaseapp.com',
    storageBucket: 'aidly-4d8d4.firebasestorage.app',
  );
}
